export const data =  [
  {
    id: 1,
    title: 'susan smith',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam',
    image:"https://bit.ly/dan-abramov",
    job:'3 jobs',
    msg:'message',
  },
  {
    id: 2,
    title: 'susan smith',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam',
    image:"https://bit.ly/dan-abramov",
    job:'3 jobs',
    msg:'message',
  },
  {
    id: 3,
    title: 'susan smith',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam',
    image:"https://bit.ly/dan-abramov",
    job:'3 jobs',
    msg:'message',
  },
  {
    id: 4,
    title: 'susan smith',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam',
    image:"https://bit.ly/dan-abramov",
    job:'3 jobs',
    msg:'message',
  },
  {
    id: 5,
    title: 'susan smith',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam',
    image:"https://bit.ly/dan-abramov",
    job:'3 jobs',
    msg:'message',
  },
  {
    id: 6,
    title: 'susan smith',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam',
    image:"https://bit.ly/dan-abramov",
    job:'3 jobs',
    msg:'message',
  },
];
